name: Eclipse Che (Single-User)
description: |
  Still doesn't work. Either a rancher-nfs issue, or eclipse-che issue.
  Might try again some other time.
version: latest
category: Development
maintainer: WilliamMiceli
license:
projectURL: https://www.eclipse.org/che/