name: OpenProject
description: |
  A web-based project management system for location-independent team collaboration.
version: latest
category: Productivity
maintainer: WilliamMiceli
# license:
# projectURL: