version: '2'

services:
  memcached:
    image: memcached:latest
    dns:
      - 1.1.1.1
      - 1.0.0.1
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
    restart: on-failure
  openproject:
    image: openproject/community:latest
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      CACHE_MEMCACHE_SERVER: memcached
      CACHE_NAMESPACE: openproject
      SECRET_KEY_BASE: ${SECRET_KEY}
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      {{- if .Values.TRAEFIK_HOST}}
      traefik.enable: true
      ### Start Web Segment
      traefik.web.frontend.entryPoints: http,https
      traefik.web.frontend.headers.forceSTSHeader: true
      traefik.web.frontend.headers.SSLRedirect: true
      traefik.web.frontend.headers.STSPreload: true
      traefik.web.frontend.headers.STSSeconds: 15552000
      traefik.web.frontend.redirect.entryPoint: https
      traefik.web.frontend.redirect.permanent: true
      traefik.web.frontend.rule: Host:${TRAEFIK_HOST}
      traefik.web.port: "80"
      ### End Web Segment
      {{- else}}
      traefik.enable: false
      {{- end}}
    links:
      - memcached
    networks:
      - public-proxy # Used for the connection to the Traefik container for public access
    ports:
      - "${WEB_PORT}:80"
    restart: on-failure
    volumes:
      - /RancherCattleData/${DATA_DIR}/Database:/var/lib/postgresql/9.6/main
      - /RancherCattleData/${DATA_DIR}/Logs:/var/log/supervisor
      - /RancherCattleData/${DATA_DIR}/Static:/var/db/openproject

networks:
  public-proxy:
    external: true