version: '2'
catalog:
  name: OpenProject
  version: latest
  # description:
  # minimum_rancher_version:
  # maximum_rancher_version:
  # upgrade_from:
  questions:

    - variable: OPENPROJECT_PORT
      label: Port
      default: 80
      required: true
      type: int

services:
  openproject:
    scale: 1
    start_on_create: true
  openproject-data:
    scale: 1
    start_on_create: true