version: '2'
catalog:
  name: openproject
  version: 0.0.1
  description: Project planning and scheduling
  questions:

    - variable: OPENPROJECT_PORT
      label: Port
      default: 80
      required: true
      type: int

services:
  openproject:
    scale: 1
    start_on_create: true
  openproject-data:
    scale: 1
    start_on_create: true