name: Apache Guacamole
description: |
  A clientless remote desktop gateway. It supports standard protocols like VNC, RDP, and SSH.
version: latest
#category:
maintainer: WilliamMiceli
# license: 
# projectURL: