version: '2'
services:
  app:
    image: invoiceninja/invoiceninja
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: http://localhost:${WEB_PORT}
      APP_CIPHER: AES-256-CBC
      APP_KEY: ${APP_KEY}
      DB_STRICT: false
      DB_HOST: ninja-mysql
      DB_DATABASE: ninja_db
      DB_USERNAME: ninja
      DB_PASSWORD: ninjaPass
    labels:
{{- if (.Values.LABEL_KEY_VALUE)}}
      io.rancher.scheduler.affinity:host_label: ${LABEL_KEY_VALUE}
{{- end}}
      io.rancher.sidekicks: cron, web
    links:
      - db:ninja-mysql
    restart: on-failure
    volumes:
      - ${STORAGE_BASE_DIR}${LOGO_DIR}:/var/www/app/public/logo
      - ${STORAGE_BASE_DIR}${STORAGE_DIR}:/var/www/app/storage
  cron:
    image: invoiceninja/invoiceninja
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1h
      done
      EOF'
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: http://localhost:${WEB_PORT}
      APP_CIPHER: AES-256-CBC
      APP_KEY: ${APP_KEY}
      DB_STRICT: false
      DB_HOST: ninja-mysql
      DB_DATABASE: ninja_db
      DB_USERNAME: ninja
      DB_PASSWORD: ninjaPass
    labels:
{{- if (.Values.LABEL_KEY_VALUE)}}
      io.rancher.scheduler.affinity:host_label: ${LABEL_KEY_VALUE}
{{- end}}
    links:
      - db:ninja-mysql
    restart: on-failure
    volumes_from:
      - app
  db:
    image: mysql:5
    environment:
      MYSQL_DATABASE: ninja_db
      MYSQL_ROOT_PASSWORD: rootPass
      MYSQL_USER: ninja
      MYSQL_PASSWORD: ninjaPass
    labels:
{{- if (.Values.LABEL_KEY_VALUE)}}
      io.rancher.scheduler.affinity:host_label: ${LABEL_KEY_VALUE}
{{- end}}
    restart: on-failure
    volumes:
      - ${STORAGE_BASE_DIR}${DB_DIR}:/var/lib/mysql
  web:
    image: nginx
    labels:
{{- if (.Values.LABEL_KEY_VALUE)}}
      io.rancher.scheduler.affinity:host_label: ${LABEL_KEY_VALUE}
{{- end}}
    links:
      - app
    ports:
      - "${WEB_PORT}:80"
    restart: on-failure
    volumes:
      - ${STORAGE_BASE_DIR}${CONFIG_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app