name: Ghost
description: |
  Ghost is a free and open source blogging platform, designed to simplify the process of online publishing.
version: latest
category: blogging
maintainer: WilliamMiceli
# license:
# projectURL: