version: '2'
catalog:
  name: traefik
  version: 2.0
  # description:
  # minimum_rancher_version:
  # maximum_rancher_version:
  # upgrade_from:
  # uuid: traefik-0
  questions:

    - variable: "HOST_LABEL"
      label: "Host Label Key/Value Pair"
      description: |
        The Key/Value pair of the host which the stack should be deployed.
      default: "host.id=Proxy0"
      required: false
      type: string

    - variable: "DATA_DIR"
      label: "Data Directory"
      description: |
        The persistent data directory.
      default: "Personal/Traefik"
      required: true
      type: string