version: '2'
catalog:
  name: "ZeroTier-Containerized" # Name of the versioned template of the Catalog Entry
  version: "latest" # Version of the versioned template of the Catalog Entry
  description: "Will fill in description later." # Description of the versioned template of the Catalog Entry
  questions: #Used to request user input for configuration options
    - variable: "CONFIG_STORAGE" # A single word that is used to pair the question and answer.
      label: "Persistent Config Path" # The "question" to be answered.
      description: | # The description of the question to show the user how to answer the question.
        The path to where ZeroTier should hold it's persistent files. Preferrably a local-only location.
      default: "/var/lib/Storage-Local/zerotier-one" # (Optional) A default value that will be pre-populated into the UI
      required: false # (Optional) Whether or not an answer is required. By default, it's considered `false`.
      type: string # How the questions are formatted and types of response expected