version: '2'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      PMA_ARBITRARY: 1 # Allows the user to specify any arbitrary server using address/hostname and port
    {{- if or .Values.SERVICE_LINK_1 .Values.SERVICE_LINK_2 .Values.SERVICE_LINK_3}}
    external_links:
      {{- if .Values.SERVICE_LINK_1}}
      - ${SERVICE_LINK_1}{{- if .Values.SERVICE_LINK_1_ALIAS}}:${SERVICE_LINK_1_ALIAS}{{- end}}
      {{- end}}
      {{- if .Values.SERVICE_LINK_2}}
      - ${SERVICE_LINK_2}{{- if .Values.SERVICE_LINK_2_ALIAS}}:${SERVICE_LINK_2_ALIAS}{{- end}}
      {{- end}}
      {{- if .Values.SERVICE_LINK_3}}
      - ${SERVICE_LINK_3}{{- if .Values.SERVICE_LINK_3_ALIAS}}:${SERVICE_LINK_3_ALIAS}{{- end}}
      {{- end}}
    {{- end}}
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: true
      ### Start Web Segment
      traefik.web.frontend.entryPoints: http,https
      traefik.web.frontend.headers.forceSTSHeader: true
      traefik.web.frontend.headers.SSLRedirect: true
      traefik.web.frontend.headers.STSPreload: true
      traefik.web.frontend.headers.STSSeconds: 15552000
      traefik.web.frontend.rule: Host:${TRAEFIK_HOST}
      traefik.web.port: "80"
      ### End Web Segment
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - /etc/timezone:/etc/timezone:ro # Syncronize timezone of container with the host system