version: '2'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      PMA_ARBITRARY: true
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      {{- if .Values.TRAEFIK_HOST}}
      traefik.enable: true
      ### Start Web Segment
      traefik.web.frontend.entryPoints: http,https
      traefik.web.frontend.headers.forceSTSHeader: true
      traefik.web.frontend.headers.SSLRedirect: true
      traefik.web.frontend.headers.STSPreload: true
      traefik.web.frontend.headers.STSSeconds: 15552000
      traefik.web.frontend.redirect.entryPoint: https
      traefik.web.frontend.redirect.permanent: true
      traefik.web.frontend.rule: Host:${TRAEFIK_HOST}
      traefik.web.port: "80"
      ### End Web Segment
      {{- else}}
      traefik.enable: false
      {{- end}}
    networks:
      - db-admin
    ports:
      - "${WEB_PORT}:80"
    restart: on-failure

networks:
  db-admin: