version: '2'

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    command:
      - register
      - --non-interactive
      - --url
      - ${GITLAB_URL}
      - --registration-token
      - ${GITLAB_TOKEN}
      - --executor
      - "docker"
      - --docker-image
      - alpine:latest
      {{- if .Values.GITLAB_RUNNER_DESCRIPTION}}
      - --description
      - ${GITLAB_RUNNER_DESCRIPTION}
      {{- end}}
      {{- if .Values.GITLAB_TAGS}}
      - --tag-list
      - ${GITLAB_TAGS}
      {{- end}}
      - --run-untagged
      - --locked=false;
      - run
    dns:
      - 1.1.1.1
      - 1.0.0.1
    {{- if .Values.GITLAB_LINK}}
    external_links:
      - ${GITLAB_LINK}{{- if .Values.GITLAB_LINK_ALIAS}}:${GITLAB_LINK_ALIAS}{{- end}}
    {{- end}}
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: false
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock