version: '2'

services:
  gitlab-runner-config:
    image: gitlab/gitlab-runner:alpine # Alpine Linux image is designed to use only Docker as the method of spawning runners
    command:
      - register
      - --non-interactive
      - --url
      - ${GITLAB_URL}
      - --registration-token
      - ${GITLAB_TOKEN}
      - --executor
      - "docker"
      - --docker-image
      - docker:latest
      {{- if .Values.GITLAB_RUNNER_DESCRIPTION}}
      - --description
      - ${GITLAB_RUNNER_DESCRIPTION}
      {{- end}}
      {{- if .Values.GITLAB_TAGS}}
      - --tag-list
      - ${GITLAB_TAGS}
      {{- end}}
      - --locked=false
    {{- if .Values.GITLAB_LINK}}
    external_links:
      - ${GITLAB_LINK}{{- if .Values.GITLAB_LINK_ALIAS}}:${GITLAB_LINK_ALIAS}{{- end}}
    {{- end}}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: true
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /RancherCattle/${DATA_DIR}:/etc/gitlab-runner
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine # Alpine Linux image is designed to use only Docker as the method of spawning runners
    command:
      - run
    {{- if .Values.GITLAB_LINK}}
    external_links:
      - ${GITLAB_LINK}{{- if .Values.GITLAB_LINK_ALIAS}}:${GITLAB_LINK_ALIAS}{{- end}}
    {{- end}}
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      io.rancher.sidekicks: gitlab-runner-config
      traefik.enable: false
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /RancherCattle/${DATA_DIR}:/etc/gitlab-runner
