name: ZeroTier-Containerized
description: |
  Will put in description later.
version: latest
category: Networking
maintainer: WilliamMiceli
license:
projectURL: https://hub.docker.com/r/zerotier/zerotier-containerized/