name: Redis
description: |
  Redis is an open-source, networked, in-memory, key-value data store with optional durability.
version: latest
# category:
maintainer: WilliamMiceli
# license:
# projectURL: