version: '2'
services:

  traefik:
    image: traefik:latest
    command: --api --docker
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: true
      io.rancher.container.hostname_override: traefik
      io.rancher.container.pull_image: always
      {{- if (.Values.HOST_LABEL)}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
    networks:
      - default
      - public
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /RancherConfig/Personal/Traefik/traefik.toml:/traefik.toml:ro
#      - /opt/traefik/acme.json:/acme.json

networks:
  public-proxy: