version: '2'
services:

  traefik:
    image: traefik:latest
    command: --api --docker
    labels:
{{- if (.Values.HOST_LABEL)}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
{{- end}}
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # container_name: traefik