version: '2'

services:
  cells:
    image: pydio/cells:latest
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    environment:
      CELLS_BIND: localhost:80
      CELLS_EXTERNAL: ${TRAEFIK_HOST}
      CELLS_NO_SSL: true
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: true
      ### Start Web Segment
      traefik.web.frontend.entryPoints: http,https
      traefik.web.frontend.headers.forceSTSHeader: true
      traefik.web.frontend.headers.referrerPolicy: no-referrer # Security enhancement (Prevents leaking of referer information)
      traefik.web.frontend.headers.SSLRedirect: true
      traefik.web.frontend.headers.STSPreload: true
      traefik.web.frontend.headers.STSSeconds: 15552000
      traefik.web.frontend.rule: Host:${TRAEFIK_HOST}
      traefik.web.port: "80"
      ### End Web Segment
    links:
      - mysql
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - /etc/timezone:/etc/timezone:ro # Syncronize timezone of container with the host system
      - /RancherCattle/${DATA_DIR}/Configuration/pydio.json:/root/.config/pydio/cells/pydio.json # Cells main configuration file
      - /RancherCattle/${DATA_DIR}/Data:/root/.config/pydio/cells/data # Cells users' data files
      - /RancherCattle/${DATA_DIR}/Logs:/root/.config/pydio/cells/logs # Cells logs
      - /RancherCattle/${DATA_DIR}/Services:/root/.config/pydio/cells/services # Cells services information
  mysql:
    image: mysql:5
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    environment:
      MYSQL_DATABASE: cells_db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: cells_user
      MYSQL_PASSWORD: ${DB_USER_PASS}
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: false
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - /etc/timezone:/etc/timezone:ro # Syncronize timezone of container with the host system
      - /RancherCattle/${DATA_DIR}/Database:/var/lib/mysql
