version: '2'

services:
  adminer:
    image: adminer:standalone
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
    environment:
      ADMINER_DESIGN: "pepa-linha"
    {{- if or .Values.SERVICE_LINK_1 .Values.SERVICE_LINK_2 .Values.SERVICE_LINK_3}}
    external_links:
      {{- if .Values.SERVICE_LINK_1}}
      - ${SERVICE_LINK_1}{{- if .Values.SERVICE_LINK_1_ALIAS}}:${SERVICE_LINK_1_ALIAS}{{- end}}
      {{- end}}
      {{- if .Values.SERVICE_LINK_2}}
      - ${SERVICE_LINK_2}{{- if .Values.SERVICE_LINK_2_ALIAS}}:${SERVICE_LINK_2_ALIAS}{{- end}}
      {{- end}}
      {{- if .Values.SERVICE_LINK_3}}
      - ${SERVICE_LINK_3}{{- if .Values.SERVICE_LINK_3_ALIAS}}:${SERVICE_LINK_3_ALIAS}{{- end}}
      {{- end}}
    {{- end}}
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      ### Begin Traefik Configuration
      traefik.enable: true
      # Routers
      traefik.http.routers.{{.Stack.Name}}-router-http.entrypoints: http
      traefik.http.routers.{{.Stack.Name}}-router-http.rule: Host(`${TRAEFIK_HOST}`)
      traefik.http.routers.{{.Stack.Name}}-router-http.middlewares: {{.Stack.Name}}-redirectHttp
      traefik.http.routers.{{.Stack.Name}}-router-http.service: {{.Stack.Name}}-service-http
      traefik.http.routers.{{.Stack.Name}}-router-https.entrypoints: https
      traefik.http.routers.{{.Stack.Name}}-router-https.rule: Host(`${TRAEFIK_HOST}`)
      traefik.http.routers.{{.Stack.Name}}-router-https.tls: true
      traefik.http.routers.{{.Stack.Name}}-router-https.tls.certresolver: letsencrypt
      traefik.http.routers.{{.Stack.Name}}-router-https.middlewares: {{.Stack.Name}}-security
      traefik.http.routers.{{.Stack.Name}}-router-https.service: {{.Stack.Name}}-service-http
      # Middlewares
      traefik.http.middlewares.{{.Stack.Name}}-redirectHttp.redirectscheme.permanent: true
      traefik.http.middlewares.{{.Stack.Name}}-redirectHttp.redirectscheme.scheme: https
      traefik.http.middlewares.{{.Stack.Name}}-security.headers.forceSTSHeader: true
      traefik.http.middlewares.{{.Stack.Name}}-security.headers.referrerPolicy: no-referrer # Prevents leaking of referer information
      traefik.http.middlewares.{{.Stack.Name}}-security.headers.sslredirect: true # Maybe good for redundancy?
      traefik.http.middlewares.{{.Stack.Name}}-security.headers.stsIncludeSubdomains: true
      traefik.http.middlewares.{{.Stack.Name}}-security.headers.stsPreload: true
      traefik.http.middlewares.{{.Stack.Name}}-security.headers.stsSeconds: "15552000"
      # Services
      traefik.http.services.{{.Stack.Name}}-service-http.loadbalancer.passhostheader: true
      traefik.http.services.{{.Stack.Name}}-service-http.loadbalancer.server.port: "8080"
      ### End Traefik Configuration
      ### End Web Segment
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - /etc/timezone:/etc/timezone:ro # Syncronize timezone of container with the host system