version: '2'

services:
  hubot:
    image: rocketchat/hubot-rocketchat:latest
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    environment:
      ROCKETCHAT_URL: hubot.${TRAEFIK_HOST}
      ROCKETCHAT_ROOM: GENERAL
      ROCKETCHAT_USER: Hubot
      ROCKETCHAT_PASSWORD: BotPassw0rd
      BOT_NAME: Hubot
      EXTERNAL_SCRIPTS: hubot-help,hubot-seen,hubot-links,hubot-greetings
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: true
      ### Start Hubot Segment
      traefik.hubot.frontend.entryPoints: http,https
      traefik.hubot.frontend.headers.forceSTSHeader: true
      traefik.hubot.frontend.headers.referrerPolicy: no-referrer # Security enhancement (Prevents leaking of referer information)
      traefik.hubot.frontend.headers.SSLRedirect: true
      traefik.hubot.frontend.headers.STSPreload: true
      traefik.hubot.frontend.headers.STSSeconds: 15552000
      traefik.hubot.frontend.passHostHeader: true
      traefik.hubot.frontend.rule: Host:${TRAEFIK_HOST}
      traefik.hubot.port: "8080"
      ### End Hubot Segment
    links:
      - rocketchat:rocketchat
    volumes:
      - /etc/localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - /etc/timezone:/etc/timezone:ro # Syncronize timezone of container with the host system
  mongo:
    image: mongo:latest
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: false
    volumes:
      - /etc/localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - /etc/timezone:/etc/timezone:ro # Syncronize timezone of container with the host system
      - /Rancher/${DATA_DIR}/Database/Data:/data/db
      - /Rancher/${DATA_DIR}/Database/Dump:/dump
    command: mongod --smallfiles
  rocketchat:
    image: rocketchat/rocket.chat:latest
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    environment:
      MONGO_URL: mongodb://mongo:27017/rocketchat
      ROOT_URL: https://${TRAEFIK_HOST}
      Accounts_UseDNSDomainCheck: true
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: true
      ### Start RocketChat Segment
      traefik.rocketchat.frontend.entryPoints: http,https
      traefik.rocketchat.frontend.headers.forceSTSHeader: true
      traefik.rocketchat.frontend.headers.referrerPolicy: no-referrer # Security enhancement (Prevents leaking of referer information)
      traefik.rocketchat.frontend.headers.SSLRedirect: true
      traefik.rocketchat.frontend.headers.STSPreload: true
      traefik.rocketchat.frontend.headers.STSSeconds: 15552000
      traefik.rocketchat.frontend.passHostHeader: true
      traefik.rocketchat.frontend.rule: Host:${TRAEFIK_HOST}
      traefik.rocketchat.port: "3000"
      ### End RocketChat Segment
    links:
      - mongo:mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - /etc/timezone:/etc/timezone:ro # Syncronize timezone of container with the host system