name: Eclipse Che
description: |
  Eclipse Che is an open-source Java based developer workspace server and cloud integrated development environment (IDE) which provides a remote development platform for multi-user purpose.
version: latest
# category:
maintainer: WilliamMiceli
# license:
projectURL: https://www.eclipse.org/che/