version: '2'

services:
  theia:
    image: theiaide/theia:next
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: true
      ### Start Web Segment
      {{- if .Values.TRAEFIK_BASIC_AUTH}}
      traefik.dashboard.frontend.auth.basic: ${TRAEFIK_BASIC_AUTH}
      {{- end}}
      traefik.frontend.entryPoints: http,https
      traefik.frontend.headers.forceSTSHeader: true
      traefik.frontend.headers.referrerPolicy: no-referrer # Security enhancement (Prevents leaking of referer information)
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.STSPreload: true
      traefik.frontend.headers.STSSeconds: 15552000
      traefik.frontend.passHostHeader: true
      traefik.frontend.rule: Host:${TRAEFIK_HOST}
      traefik.port: "3000"
      ### End Web Segment
    restart: on-failure
    volumes:
      - /RancherCattle/${DATA_DIR}/Project:/home/project:cached