version: '2'

services:
  ghost:
    image: ghost:latest
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      {{- if .Values.TRAEFIK_HOST}}
      node_env: production
      url: https://${TRAEFIK_HOST}
      {{- end}}
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      {{- if .Values.TRAEFIK_HOST}}
      traefik.enable: true
      traefik.frontend.rule: Host:${TRAEFIK_HOST}
      traefik.port: "2368"
      traefik.frontend.entryPoints: https
      {{- else}}
      traefik.enable: false
      {{- end}}
    networks:
      - public-proxy
    ports:
      - "${WEB_PORT}:2368"
    restart: on-failure
    volumes:
      - Content:/var/lib/ghost/content

networks:
  public-proxy:
    external: true

volumes:
  Content:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.10.21
      export: /RancherCattleData/${DATA_DIR}/Content
      onRemove: retain