version: '2'
catalog:
  name: Ghost
  version: latest
  # description:
  # minimum_rancher_version:
  # maximum_rancher_version:
  # upgrade_from:
  uuid: ghost-0
  questions:

    - variable: public_port
      description: "public port to access the blog"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"

ghost: