version: '2'
catalog:
  name: Ghost
  version: latest
  # description:
  # minimum_rancher_version:
  # maximum_rancher_version:
  # upgrade_from:
  # uuid: ghost-0
  questions:

    - variable: "HOST_LABEL"
      label: "Host Label Key/Value Pair"
      description: |
        The Key/Value pair on the host which the stack should be deployed.
      default: "host.id=Host1"
      required: false
      type: string

    - variable: "TRAEFIK_HOST"
      label: "Public Host Domain"
      description: |
        The host that Traefik will use to provide public access.
        Leaving this empty will disable Traefik on this stack.
      default: "subdomain.domain.tld"
      required: false
      type: string

    - variable: "WEB_PORT"
      label: "Web Port"
      description: |
        The port to access the web interface on.
      default: "10400"
      required: true
      type: string

    - variable: "DATA_DIR"
      label: "Data Directory"
      description: |
        The persistent data directory
      default: "Personal/Ghost"
      required: true
      type: string

ghost: