.catalog:
  name: "Ghost"
  version: "v0.1-educaas"
  description: "Blog powered by Ghost. Requires no database"
  uuid: ghost-0
  questions:

    - variable: public_port
      description: "public port to access the blog"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"

ghost: