version: '2'

services:
  cryptpad:
    image: cryptpad/cryptpad:latest
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: true
      ### Start Web Segment
      traefik.frontend.entryPoints: http,https
      traefik.frontend.headers.forceSTSHeader: true
      traefik.frontend.headers.referrerPolicy: no-referrer # Security enhancement (Prevents leaking of referer information)
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.STSPreload: true
      traefik.frontend.headers.STSSeconds: 15552000
      traefik.frontend.passHostHeader: true
      traefik.frontend.rule: Host:${TRAEFIK_HOST}
      traefik.port: "3000"
      ### End Web Segment
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - /etc/timezone:/etc/timezone:ro # Syncronize timezone of container with the host system
      - /RancherCattle/${DATA_DIR}/Blob:/cryptpad/blob
      - /RancherCattle/${DATA_DIR}/BlobStage:/cryptpad/blobstage
      - /RancherCattle/${DATA_DIR}/Block:/cryptpad/block
      - /RancherCattle/${DATA_DIR}/Configuration:/cryptpad/customize
      - /RancherCattle/${DATA_DIR}/Data:/cryptpad/datastore
      - /RancherCattle/${DATA_DIR}/Pins:/cryptpad/pins
      - /RancherCattle/${DATA_DIR}/Tasks:/cryptpad/tasks