name: Nextcloud
description: |
  Nextcloud is a suite of client-server software for creating and using file hosting services.
version: latest
# category:
maintainer: WilliamMiceli
# license:
# projectURL: https://github.com/ellerbrock/rancher-collection