version: '2'

services:
  gogs:
    image: gogs/gogs:latest
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      RUN_CROND: true
      SOCAT_LINK: false # Being used inside of Rancher
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      {{- if .Values.TRAEFIK_HOST}}
      traefik.enable: true
      traefik.frontend.rule: Host:${TRAEFIK_HOST}
      traefik.frontend.entryPoints: http,https
      traefik.frontend.headers.forceSTSHeader: true
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.STSPreload: true
      traefik.frontend.headers.STSSeconds: 15552000
      traefik.port: "3000"
      {{- else}}
      traefik.enable: false
      {{- end}}
    links:
      - mysql
    networks:
      - public-proxy
    ports:
      - "${SSH_PORT}:22"
      - "${WEB_PORT}:3000"
    restart: on-failure
    volumes:
      - /RancherCattleData/${DATA_DIR}/Data:/data
  mysql:
    image: mysql:5
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      MYSQL_DATABASE: gogs
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: gogs_user
      MYSQL_PASSWORD: ${DB_USER_PASS}
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
    restart: on-failure
    volumes:
      - /RancherCattleData/${DATA_DIR}/Database:/var/lib/mysql

networks:
  public-proxy:
    external: true