name: GitLab (Community Edition)
description: |
  GitLab is a web-based Git-repository manager providing wiki, issue-tracking and CI/CD pipeline features.
version: latest
# category:
maintainer: WilliamMiceli
# license:
projectURL: https://hub.docker.com/r/gitlab/gitlab-ce/