version: '2'
services:

  snipe-it:
    image: snipe/snipe-it:latest
    depends_on:
      - mysql
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      APP_ENV: production
      APP_DEBUG: false
      {{- if .Values.TRAEFIK_HOST}}
      APP_URL: https://${TRAEFIK_HOST}
      {{- else}}
      APP_URL: http://localhost:${WEB_PORT}
      {{- end}}
      APP_KEY: ${APP_KEY}
      MYSQL_HOST: mysql
      MYSQL_DATABASE: snipeit
      MYSQL_USER: snipe_user
      MYSQL_PASSWORD: ${DB_USER_PASS}
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      {{- if .Values.TRAEFIK_HOST}}
      traefik.enable: true
      traefik.frontend.rule: Host:${TRAEFIK_HOST}
      traefik.frontend.entryPoints: http,https
      traefik.frontend.headers.forceSTSHeader: true
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.STSPreload: true
      traefik.frontend.headers.SSLProxyHeaders: X-Forwarded-Proto:https
      traefik.frontend.headers.STSSeconds: 15552000
      traefik.port: "80"
      {{- else}}
      traefik.enable: false
      {{- end}}
    links:
      - mysql
    networks:
      - public-proxy
    {{- if .Values.WEB_PORT}}
    ports:
      - "${WEB_PORT}:80"
    {{- else}}
    expose:
      - "80"
    {{- end}}
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - /etc/timezone:/etc/timezone:ro # Syncronize timezone of container with the host system
      - /RancherCattleData/${DATA_DIR}/Application:/var/lib/snipeit
      - /RancherCattleData/${DATA_DIR}/Backups:/var/www/html/storage/app/backups
  mysql:
    image: mysql:5
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      MYSQL_DATABASE: snipeit
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: snipe_user
      MYSQL_PASSWORD: ${DB_USER_PASS}
    labels:
      io.rancher.container.pull_image: always
      {{- if (.Values.HOST_LABEL)}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - /etc/timezone:/etc/timezone:ro # Syncronize timezone of container with the host system
      - /RancherCattleData/${DATA_DIR}/Database:/var/lib/mysql

networks:
  public-proxy:
    external: true