version: '2'
catalog:
  name: WordPress
  version: latest
  # description:
  # minimum_rancher_version:
  # maximum_rancher_version:
  # upgrade_from:
  questions:

    - variable: "HOST_LABEL"
      label: "Host Label Key/Value Pair"
      description: |
        The Label Key/Value pair on the host which containers should be deployed
      default: "host.id=Host1"
      required: false
      type: string

    - variable: "TRAEFIK_HOST"
      label: "Public Host Domain"
      description: |
        The host that Traefik will use to provide public access.
        Leaving this empty will disable Traefik on this stack.
      default: "subdomain.domain.tld"
      required: false
      type: string

    - variable: "WEB_PORT"
      label: "Web Port"
      description: |
        The port to locally access the web interface on.
      default: "10600"
      required: true
      type: string

    - variable: "DB_ROOT_PASS"
      label: "MySQL Root Password"
      description: |
        A secure password to be used by the "root" MySQL user.
      # default:
      required: true
      type: password

    - variable: "DB_USER_PASS"
      label: "MySQL User Password"
      description: |
        A secure password to be used by the "wordpress_user" MySQL user.
      # default:
      required: true
      type: password

    - variable: "DATA_DIR"
      label: "Data Directory"
      description: |
        The directory to store persistent data for the stack.
      default: "Personal/Wordpress"
      required: true
      type: string

services:
  wordpress:
    scale: 1
  mysql:
    scale: 1