name: Eclipse Che (Single-User)
description: |
  Not yet operational.
  Permissions issues, but almost there...
version: latest
category: Development
maintainer: WilliamMiceli
license:
projectURL: https://www.eclipse.org/che/