name: WordPress
description: |
  WordPress is open source software you can use to create a beautiful website, blog, or app.
version: latest
# category:
maintainer: WilliamMiceli
# license:
# projectURL: