name: Invoice Ninja
description: |
  Will put in description later.
version: latest
category: Invoicing
maintainer: WilliamMiceli
license:
projectURL: https://hub.docker.com/r/invoiceninja/invoiceninja/