version: '2'

services:
  mongo:
    image: mongo:3
    command: '--smallfiles --bind_ip ::,0.0.0.0'
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    environment:
      MONGO_LOG_DIR: /dev/null
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - /etc/timezone:/etc/timezone:ro # Syncronize timezone of container with the host system
      - /Rancher/${DATA_DIR}/Database/Data:/data/db
      - /Rancher/${DATA_DIR}/Database/Dump:/dump
  wikijs:
    image: requarks/wiki:latest # v1 Only
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    environment:
      WIKI_ADMIN_EMAIL: ${ADMIN_EMAIL}
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: true
      ### Start Web Segment
      traefik.web.frontend.entryPoints: http, https
      traefik.web.frontend.headers.forceSTSHeader: true
      traefik.web.frontend.headers.referrerPolicy: no-referrer # Security enhancement (Prevents leaking of referer information)
      traefik.web.frontend.headers.SSLRedirect: true
      traefik.web.frontend.headers.STSPreload: true
      traefik.web.frontend.headers.STSSeconds: 15552000
      traefik.web.frontend.passHostHeader: true
      traefik.web.frontend.rule: "Host:${TRAEFIK_HOST}"
      traefik.web.port: "80"
      ### End Web Segment
    links:
      - mongo
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - /etc/timezone:/etc/timezone:ro # Syncronize timezone of container with the host system
      - /Rancher/${DATA_DIR}/Wiki/config.yml:/var/wiki/config.yml
