grafana:
  image: grafana/grafana:4.2.0
  labels:
    io.rancher.container.pull_image: always
  ports:
    - ${http_port}:3000
  environment:
    GF_SECURITY_ADMIN_USER: ${admin_username}
    GF_SECURITY_ADMIN_PASSWORD: ${admin_password}
    GF_SECURITY_SECRET_KEY: ${secret_key}
    GF_INSTALL_PLUGINS: ${install_plugins}