version: "2"

services:
  matomo:
    image: matomo:3.5-apache
    restart: always
    links:
      - db
    volumes:
      - "./config:/var/www/html/config:rw"
      - "./logs:/var/www/html/logs"
    environment:
      VIRTUAL_HOST: CHANGE_ME
    ports:
      - "80:80"

  db:
    image: mariadb:latest
    volumes:
      - ./mysql/runtime2:/var/lib/mysql
    environment:
      MYSQL_DATABASE: matomo_db
      MYSQL_ROOT_PASSWORD: CHANGE_ME
      MYSQL_USER: matomo_user
      MYSQL_PASSWORD: CHANGE_ME