version: '2'
services:
  che-server:
    image: eclipse/che-server:latest
    container_name: eclipse-che
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - CHE_HOST=${HOST_IP}
      - CHE_PORT=${CHE_PORT}
    labels:
      io.rancher.scheduler.affinity:host_label: ${LABEL_KEY_VALUE}
    ports:
      - "${CHE_PORT}:8080"
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STORAGE_BASE_DIR}${DATA_DIR}:/data
      - ${STORAGE_BASE_DIR}${REPO_DIR}:/repo