version: '2'
services:
  che-server:
    image: eclipse/che-server:latest
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      CHE_DOCKER_IP_EXTERNAL: ${EXTERNAL_IP}
      CHE_HOST: ${TRAEFIK_HOST}
      CHE_IN_VM: true
      CHE_SINGLE_PORT: true
      CHE_SINGLEPORT_WILDCARD__DOMAIN_HOST: ${WILDCARD_DNS}
      CHE_SINGLEPORT_WILDCARD__DOMAIN_IPLESS: true
    expose:
      - "8080"
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      {{- if .Values.TRAEFIK_HOST}}
      traefik.enable: true
      traefik.port: "8080"
      {{- if .Values.TRAEFIK_BASIC_AUTH}}
      traefik.frontend.auth.basic: ${TRAEFIK_BASIC_AUTH}
      {{- end}}
      traefik.frontend.entryPoints: http,https
      traefik.frontend.rule: Host:${TRAEFIK_HOST}
      traefik.frontend.passHostHeader: true
      {{- else}}
      traefik.enable: false
      {{- end}}
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /RancherCattleData/${DATA_DIR}/Data:/data
      - /RancherCattleData/${DATA_DIR}/Repo:/repo