version: '2'
services:
  che-server:
    image: eclipse/che-server:latest
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      CHE_HOST: ${HOST_IP}
      CHE_IN_VM: true
    labels:
      io.rancher.container.pull_image: always
      {{- if (.Values.HOST_LABEL)}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
    ports:
      - "${CHE_PORT}:8080"
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - Data:/data
      - Repo:/repo

volumes:
  Data:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.10.21
      export: /RancherCattleData/${DATA_DIR}/Data
      onRemove: retain
  Repo:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.10.21
      export: /RancherCattleData/${DATA_DIR}/Repo
      onRemove: retain