version: '2'
services:
  invoiceninja:
    image: invoiceninja/invoiceninja
    environment:
      - APP_ENV='production'
      - APP_DEBUG=0
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - APP_CIPHER='AES-256-CBC'
      - DB_TYPE='mysql'
      - DB_STRICT='false'
      - DB_HOST='localhost'
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    labels:
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL_KEY}=${HOST_LABEL_VALUE}
    links:
      - db:mysql
    restart: always
    volumes:
      - ${VOLUME_LOGO}:/var/www/app/public/logo:nocopy
      - ${VOLUME_STORAGE}:/var/www/app/storage:nocopy
  cron:
    image: invoiceninja/invoiceninja
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1h
      done
      EOF'
    environment:
      - APP_ENV='production'
      - APP_DEBUG=0
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - APP_CIPHER='AES-256-CBC'
      - DB_TYPE='mysql'
      - DB_STRICT='false'
      - DB_HOST='localhost'
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    links:
      - db:mysql
  db:
    image: mysql
    environment:
      - APP_ENV='production'
      # - APP_DEBUG=0
      # - APP_URL=${APP_URL}
      # - APP_KEY=${APP_KEY}
      # - APP_CIPHER='AES-256-CBC'
      # - DB_TYPE='mysql'
      # - DB_STRICT='false'
      # - DB_HOST='localhost'
      # - DB_DATABASE=${DB_DATABASE}
      # - DB_USERNAME=${DB_USERNAME}
      # - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - ${VOLUME_DATA}:/var/lib/mysql:nocopy
  web:
    image: nginx
    links:
      - invoiceninja
    ports:
      - 8000:80
    volumes:
      - ${VOLUME_WEB}:/etc/nginx/nginx.conf:ro
volumes_driver: rancher-nfs