version: '2'
services:
  app:
    image: invoiceninja/invoiceninja
    depends_on:
      - db
    labels:
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL_KEY}=${HOST_LABEL_VALUE}
      io.rancher.sidekicks: cron, db, web
    networks:
      - ninja-net
    restart: always
    volumes:
      - ${VOLUME_LOGO}:/var/www/app/public/logo:nocopy
      - ${VOLUME_STORAGE}:/var/www/app/storage:nocopy
  cron:
    image: invoiceninja/invoiceninja
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1h
      done
      EOF'
    labels:
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL_KEY}=${HOST_LABEL_VALUE}
    networks:
      - ninja-net
    volumes_from:
      - app
  db:
    image: mysql
    labels:
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL_KEY}=${HOST_LABEL_VALUE}
    restart: always
    volumes:
      - ${VOLUME_DATA}:/var/lib/mysql:nocopy
  web:
    image: nginx
    depends_on:
      - app
    labels:
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL_KEY}=${HOST_LABEL_VALUE}
    networks:
      - ninja-net
    ports:
      - "8000:80"
    volumes:
      - ${VOLUME_WEB}:/etc/nginx:nocopy
    volumes_from:
      - app
environment:
  - APP_DEBUG=0
  - APP_ENV='production'
  - APP_URL=${APP_URL}
  - APP_KEY=${APP_KEY}
  - APP_CIPHER='AES-256-CBC'
  - DB_HOST='mysql'
  - DB_STRICT='false'
  - DB_TYPE='mysql'
  - DB_USERNAME='ninja'
  - DB_PASSWORD='pwd'
  - MAIL_HOST='mail.service.host'
  - MAIL_DRIVER='smtp'
  - MAIL_FROM_ADDRESS='user@mail.com'
  - MAIL_FROM_NAME='My name'
  - MAIL_USERNAME='username'
  - MAIL_PASSWORD='password'
  - MYSQL_DATABASE='ninja'
  - MYSQL_ROOT_PASSWORD='pwd'
networks:
  ninja-net:
volumes_driver: rancher-nfs