version: '2'
services:
  invoiceninja:
    image: invoiceninja/invoiceninja
    environment:
      - APP_ENV='production'
      - APP_DEBUG=0
      - APP_URL='http://ninja.dev'
      -e APP_KEY=${APP_KEY}
      -e APP_CIPHER='AES-256-CBC'
      -e DB_TYPE='mysql'
      -e DB_STRICT='false'
      -e DB_HOST='localhost'
      -e DB_DATABASE=${DB_DATABASE}
      -e DB_USERNAME=${DB_USERNAME}
      -e DB_PASSWORD=${DB_PASSWORD}
    labels:
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL_KEY}=${HOST_LABEL_VALUE}
    links:
      - db:mysql
    restart: always
    volumes:
      - ${VOLUME_LOGO}:/var/www/app/public/logo:nocopy
      - ${VOLUME_STORAGE}:/var/www/app/storage:nocopy
  cron:
    image: invoiceninja/invoiceninja
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1h
      done
      EOF'
    environment:
      - APP_ENV='production'
      - APP_DEBUG=0
      - APP_URL='http://ninja.dev'
      -e APP_KEY=${APP_KEY}
      -e APP_CIPHER='AES-256-CBC'
      -e DB_TYPE='mysql'
      -e DB_STRICT='false'
      -e DB_HOST='localhost'
      -e DB_DATABASE=${DB_DATABASE}
      -e DB_USERNAME=${DB_USERNAME}
      -e DB_PASSWORD=${DB_PASSWORD}
    links:
      - db:mysql
    volumes_from:
      - invoiceninja
  db:
    image: mysql
    environment:
      - APP_ENV='production'
      - APP_DEBUG=0
      - APP_URL='http://ninja.dev'
      -e APP_KEY=${APP_KEY}
      -e APP_CIPHER='AES-256-CBC'
      -e DB_TYPE='mysql'
      -e DB_STRICT='false'
      -e DB_HOST='localhost'
      -e DB_DATABASE=${DB_DATABASE}
      -e DB_USERNAME=${DB_USERNAME}
      -e DB_PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - ${VOLUME_DATA}:/var/lib/mysql:nocopy
  web:
    image: nginx
    links:
      - invoiceninja
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - invoiceninja
volumes_driver: rancher-nfs