name: XWiki
description: |
  XWiki is a free wiki software platform written in Java with a design emphasis on extensibility.
version: latest
category: Wiki
maintainer: WilliamMiceli
# license:
# projectURL: