name: Invoice Ninja
description: |
  An open-source platform to invoice, track payments, expenses, and time billable tasks for clients.
version: latest
category: Invoicing
maintainer: WilliamMiceli
# license:
projectURL: https://hub.docker.com/r/invoiceninja/invoiceninja/