version: '2'
services:

  nextcloud:
    image: nextcloud:stable-apache
    depends_on:
      - mysql
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud_user
      MYSQL_PASSWORD: ${DB_USER_PASS}
      NEXTCLOUD_ADMIN_USER: ${NC_ADMIN}
      NEXTCLOUD_ADMIN_PASSWORD: ${NC_ADMIN_PASS}
    labels:
      # io.rancher.container.hostname_override: container_name
{{- if (.Values.HOST_LABEL)}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
{{- end}}
    networks:
      - nextcloud-net
    ports:
      - "${HOST_HTTP_PORT}:80"
    restart: on-failure
    volumes:
      - ${STORAGE_BASE_DIR}${APP_DIR}:/var/www/html
      - ${STORAGE_BASE_DIR}${DATA_DIR}:/var/www/html/data

  mysql:
    image: mysql:5
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: nextcloud_user
      MYSQL_PASSWORD: ${DB_USER_PASS}
    labels:
{{- if (.Values.HOST_LABEL)}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
{{- end}}
    networks:
      - nextcloud-net
    restart: on-failure
    volumes:
      - ${STORAGE_BASE_DIR}${DB_DIR}:/var/lib/mysql

networks:
  nextcloud-net:
    driver: bridge