version: '2'

services:
  {{- if eq .Values.COLLABORA "true"}}
  collabora:
    image: collabora/code:latest
    cap_add:
      - MKNOD # Ability to create special files (https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities)
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    environment:
      domain: collabora.${TRAEFIK_HOST}
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: false
    restart: on-failure
    volumes:
      - Localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - Timezone:/etc/timezone:ro # Syncronize timezone of container with the host system
  {{- end}}
  cron:
    image: nextcloud:fpm-alpine
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    entrypoint: | # www-data uid: 82
      sh -c 'sh -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/sh" -c "/usr/local/bin/php /var/www/html/cron.php" www-data
        echo $$(date) - Running cron finished
        sleep 900
      done
      EOF'
    restart: on-failure
    user: "www-data"
    volumes_from:
      - nginx
  nextcloud:
    image: nextcloud:fpm-alpine
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: nextcloud_db
      MYSQL_USER: nextcloud_user
      MYSQL_PASSWORD: ${DB_USER_PASS}
      NEXTCLOUD_ADMIN_USER: ${NC_ADMIN}
      NEXTCLOUD_ADMIN_PASSWORD: ${NC_ADMIN_PASS}
      NEXTCLOUD_TRUSTED_DOMAINS: ${TRAEFIK_HOST}
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: false
    links:
      - mysql
      {{- if eq .Values.REDIS "true"}}
      - redis
      {{- end}}
    restart: on-failure
    volumes_from:
      - nginx
  nginx:
    image: nginx:latest # Can't use ":alpine" until I have a way to get the "www-data" user added automatically. (Project for another time)
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      io.rancher.sidekicks: cron, nextcloud
      traefik.enable: true
      ### Start Nextcloud Segment
      traefik.nextcloud.frontend.entryPoints: http,https
      traefik.nextcloud.frontend.headers.forceSTSHeader: true
      traefik.nextcloud.frontend.headers.referrerPolicy: no-referrer # Security enhancement (Prevents leaking of referer information)
      traefik.nextcloud.frontend.headers.SSLRedirect: true
      traefik.nextcloud.frontend.headers.STSPreload: true
      traefik.nextcloud.frontend.headers.STSSeconds: 15552000
      traefik.nextcloud.frontend.rule: Host:${TRAEFIK_HOST}
      traefik.nextcloud.port: "80"
      ### End Nextcloud Segment
      ### Start Collabora Segment
      traefik.collabora.frontend.entryPoints: http,https
      traefik.collabora.frontend.headers.forceSTSHeader: true
      traefik.collabora.frontend.headers.referrerPolicy: no-referrer # Security enhancement (Prevents leaking of referer information)
      traefik.collabora.frontend.headers.SSLRedirect: true
      traefik.collabora.frontend.headers.STSPreload: true
      traefik.collabora.frontend.headers.STSSeconds: 15552000
      traefik.collabora.frontend.rule: Host:collabora.${TRAEFIK_HOST}
      traefik.collabora.port: "81"
      ### End Collabora Segment
    links:
      {{- if eq .Values.COLLABORA "true"}}
      - collabora
      {{- end}}
      - nextcloud
    networks:
      - public-proxy
    {{- if .Values.WEB_PORT}}
    ports:
      - "${WEB_PORT}:80"
    {{- end}}
    restart: on-failure
    volumes:
      - Localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - Timezone:/etc/timezone:ro # Syncronize timezone of container with the host system
      - Apps:/var/www/html/custom_apps # Nextcloud apps
      - Configuration-Nextcloud:/var/www/html/config # Nextcloud configuration files
      - Configuration-NGINX:/etc/nginx # NGINX configuration files
      - Nextcloud:/var/www/html # Nextcloud site
      - UserData:/var/www/html/data # Users' data file
  mysql:
    image: mysql:5
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    environment:
      MYSQL_DATABASE: nextcloud_db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: nextcloud_user
      MYSQL_PASSWORD: ${DB_USER_PASS}
    labels:
      io.rancher.container.hostname_override: "nextcloud"
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: false
    networks:
      db-admin:
        aliases:
          - nextcloud
    restart: on-failure
    volumes:
      - Localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - Timezone:/etc/timezone:ro # Syncronize timezone of container with the host system
      - mysql:/var/lib/mysql
  {{- if eq .Values.REDIS "true"}}
  redis:
    image: redis:alpine
    dns: # Using Cloudflare DNS
      - 1.1.1.1
      - 1.0.0.1
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      traefik.enable: false
    restart: on-failure
    volumes:
      - Localtime:/etc/localtime:ro # Syncronize time of container with the host system
      - Timezone:/etc/timezone:ro # Syncronize timezone of container with the host system
  {{- end}}

volumes:
  Localtime:
    driver_opts:
      type: none
      device: /etc/localtime
      o: bind
  Timezone:
    driver_opts:
      type: none
      device: /etc/timezone
      o: bind
  Database:
    driver_opts:
      type: none
      device: /RancherCattle/${DATA_DIR}/Database
      o: bind
  Configuration-Nextcloud:
    driver_opts:
      type: none
      device: /RancherCattle/${DATA_DIR}/Configuration/Nextcloud
      o: bind
  Configuration-NGINX:
    driver_opts:
      type: none
      device: /RancherCattle/${DATA_DIR}/Configuration/NGINX
      o: bind
  Apps:
    driver_opts:
      type: none
      device: /RancherCattle/${DATA_DIR}/Apps
      o: bind
  Nextcloud:
    driver_opts:
      type: none
      device: /RancherCattle/${DATA_DIR}/Nextcloud
      o: bind
  UserData:
    driver_opts:
      type: none
      device: /RancherCattle/${DATA_DIR}/UserData
      o: bind
  Logs-Nextcloud:
    driver_opts:
      type: none
      device: /RancherCattle/${DATA_DIR}/Logs/Nextcloud
      o: bind
  Logs-NGINX:
    driver_opts:
      type: none
      device: /RancherCattle/${DATA_DIR}/Logs/NGINX
      o: bind