version: '2'

services:
  nextcloud:
    image: nextcloud:stable-apache
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud_user
      MYSQL_PASSWORD: ${DB_USER_PASS}
      NEXTCLOUD_ADMIN_USER: ${NC_ADMIN}
      NEXTCLOUD_ADMIN_PASSWORD: ${NC_ADMIN_PASS}
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
      {{- if .Values.TRAEFIK_HOST}}
      traefik.enable: true
      traefik.frontend.rule: Host:${TRAEFIK_HOST}
      traefik.port: "80"
      traefik.frontend.entryPoints: https
      {{- else}}
      traefik.enable: false
      {{- end}}
    links:
      - mysql
    networks:
      - public-proxy
    ports:
      - "${WEB_PORT}:80"
    restart: on-failure
    volumes:
      - Application:/var/www/html
      - UserData:/var/www/html/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  mysql:
    image: mysql:5
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: nextcloud_user
      MYSQL_PASSWORD: ${DB_USER_PASS}
    labels:
      io.rancher.container.pull_image: always
      {{- if .Values.HOST_LABEL}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
      {{- end}}
    restart: on-failure
    volumes:
      - Database:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  public-proxy:
    external: true

volumes:
  Application:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.10.21
      export: /RancherCattleData/${DATA_DIR}/Application
      onRemove: retain
  Database:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.10.21
      export: /RancherCattleData/${DATA_DIR}/Database
      onRemove: retain
  UserData:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.10.21
      export: /RancherCattleData/${DATA_DIR}/UserData
      onRemove: retain