name: RocketChat
description: |
  Rocket.Chat is free, unlimited and open source. Replace email, HipChat & Slack with the ultimate team chat software solution.
version: latest
category: Communication
maintainer: WilliamMiceli
# license:
# projectURL: