version: '2'
catalog:
  name: Guacamole
  version: latest
  # description:
  # minimum_rancher_version:
  # maximum_rancher_version:
  # upgrade_from:
  # uuid:
  questions:

    - variable: "HOST_LABEL"
      label: "Host Label Key/Value Pair"
      description: |
        The Key/Value pair on the host which the stack should be deployed.
      default: "host.id=Host1"
      required: false
      type: string

    - variable: "TRAEFIK_HOST"
      label: "Public Host Domain"
      description: |
        The host that Traefik will use to provide public access.
        Leaving this empty will disable Traefik on this stack.
      default: "subdomain.domain.tld"
      required: false
      type: string

    - variable: "WEB_PORT"
      label: "Local Web Port"
      description: |
        The port to locally access the web interface on.
      default: "10700"
      required: true
      type: string